Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,25 +9,21 @@ jobs:
 
     steps:
 
-      # 1. Checkout
       - name: Checkout
         uses: actions/checkout@v4
 
 
-      # 2. Java 17
-      - name: Setup JDK
+      - name: Setup JDK 17
         uses: actions/setup-java@v4
         with:
           distribution: temurin
           java-version: '17'
 
 
-      # 3. Android SDK
       - name: Setup Android SDK
         uses: android-actions/setup-android@v3
 
 
-      # 4. Install Android SDK
       - name: Install Android SDK
         run: |
           yes | sdkmanager --licenses || true
@@ -39,56 +35,45 @@ jobs:
           sdkmanager "build-tools;35.0.0"
 
 
-      # 5. Check files
-      - name: Check Project Files
-        run: |
-          echo "Current directory:"
-          pwd
-
-          echo "Files:"
-          find . -maxdepth 4 -type f | sort
-
-
-      # 6. Gradle permission
       - name: Grant Gradle Permission
         run: |
           chmod +x gradlew
 
 
-      # 7. Gradle version
       - name: Check Gradle
         run: |
           ./gradlew --version
 
 
-      # 8. Build APK
-      - name: Build Debug APK
+      - name: Build APK
         run: |
-          ./gradlew :app:assembleDebug --stacktrace --info
+          ./gradlew :app:assembleDebug --stacktrace
 
 
-      # 9. Show output
-      - name: Show Build Output
-        if: always()
+      - name: Find APK
         run: |
           echo "=============================="
-          echo "BUILD DIRECTORY"
-          echo "=============================="
-
-          find . -type d -name "build" -print
-
-          echo "=============================="
-          echo "ALL APK FILES"
+          echo "SEARCHING APK"
           echo "=============================="
 
           find . -type f -name "*.apk" -print
 
+          APK=$(find . -type f -name "*.apk" | head -n 1)
 
-      # 10. Upload APK
+          if [ -z "$APK" ]; then
+            echo "ERROR: APK NOT FOUND"
+            exit 1
+          fi
+
+          echo "APK FOUND:"
+          echo "$APK"
+
+          cp "$APK" app-debug.apk
+
+
       - name: Upload APK
-        if: success()
         uses: actions/upload-artifact@v4
         with:
           name: app-debug
-          path: app/build/outputs/apk/debug/app-debug.apk
+          path: app-debug.apk
           if-no-files-found: error
