Update Android Project

diff --git a/.github/workflows/rebuild.yml b/.github/workflows/rebuild.yml
--- a/.github/workflows/rebuild.yml
+++ b/.github/workflows/rebuild.yml
@@ -4,13 +4,10 @@ on:
   workflow_dispatch:
 
 jobs:
-
   rebuild:
-
     runs-on: ubuntu-latest
 
     steps:
-
       - name: Checkout project
         uses: actions/checkout@v4
 
@@ -30,16 +27,19 @@ jobs:
       - name: Clean project
         run: ./gradlew clean
 
-      - name: Rebuild project
+      - name: Rebuild Debug APK
         run: ./gradlew assembleDebug
 
-      - name: Find APK
+      - name: Verify APK
         run: |
-          find . -type f -name "*.apk"
+          if [ ! -f app/build/outputs/apk/debug/app-debug.apk ]; then
+            echo "ERROR: APK was not created."
+            exit 1
+          fi
 
-      - name: Upload APK
+      - name: Upload rebuilt APK
         uses: actions/upload-artifact@v4
         with:
-          name: rebuild-apk
-          path: "**/build/outputs/apk/**/*.apk"
+          name: rebuilt-apk
+          path: app/build/outputs/apk/debug/app-debug.apk
           if-no-files-found: error
